(() => {
const C=window.VESTIGIO_CONFIG;
const dec=s=>{try{return decodeURIComponent(Array.from(atob(s)).map(c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join(''))}catch{return atob(s)}};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ');
const fresh=()=>({session:'VST-'+Date.now().toString(36).toUpperCase(),first:new Date().toISOString(),started:false,completed:[],answers:{},attempts:{},hints:{},sound:false});
let state;try{state=JSON.parse(localStorage.getItem(C.meta.storageKey))||fresh()}catch{state=fresh()}
let active=null,current=null,holdTimer,taps=0,tapTimer;
const save=()=>{try{localStorage.setItem(C.meta.storageKey,JSON.stringify(state))}catch{} renderStatus()};
const scenes={boot,intro,hub,level,reveal,book,letter};
function show(name,chrome=true){Object.values(scenes).forEach(s=>s.classList.remove('active'));scenes[name].classList.add('active');current=name;topbar.classList.toggle('hidden',!chrome);footer.classList.toggle('hidden',!chrome);scrollTo(0,0)}
async function bootRun(){for(const [t,d] of [['Inicializando sesión…',700],['Buscando registros…',800],['Verificando origen…',800],['Sincronizando memoria…',900]]){bootText.textContent=t;await new Promise(r=>setTimeout(r,d))}bootText.textContent='Coincidencias encontradas: 1';await new Promise(r=>setTimeout(r,650));identity.innerHTML='<span>Identidad vinculada</span><strong>'+C.meta.player+'</strong>';await new Promise(r=>setTimeout(r,800));bootText.textContent='Acceso concedido.';bootContinue.classList.remove('concealed')}
function unlocked(l){if(l.number===1)return state.started;return state.completed.includes(C.levels[l.number-2].id)}
function renderStatus(){session.textContent='SESIÓN: '+state.session;storage.textContent='ALMACENAMIENTO: LOCAL ACTIVO'}
function renderHub(){count.textContent=state.completed.length+' / 4';progress.style.width=(state.completed.length*25)+'%';let days=Math.floor((Date.now()-new Date(state.first).getTime())/86400000);returnText.textContent=days>0?'Han pasado '+days+' días desde la primera señal. El rumbo continúa intacto.':'La sesión de '+C.meta.player+' está activa.';records.innerHTML='';C.levels.forEach(l=>{let done=state.completed.includes(l.id),u=unlocked(l),b=document.createElement('button');b.className='record'+(done?' complete':'');b.disabled=!u;b.innerHTML='<div class="record-top"><small>REGISTRO 0'+l.number+'</small><span class="record-status">'+(done?'RECUPERADO':u?'DISPONIBLE':'BLOQUEADO')+'</span></div><h3>'+l.title+'</h3><p>'+l.subtitle+'</p>';b.onclick=()=>openLevel(l.id);records.append(b)})}
function puzzleHTML(id){
if(id==='orientation')return `<p class="caesar">URVD QR HV HO ILQDO</p><div class="compass" aria-label="Brújula desviada"></div><p>Una dirección incorrecta puede ser la dirección exacta.</p><button type="button" class="secondary" id="copyCipher">Copiar mensaje</button>`;
if(id==='essence')return `<div class="poem"><b>S</b>olo algunas cosas permanecen cuando nadie mira.<br><b>O</b>tras se quedan suspendidas en el aire.<br><b>L</b>as más difíciles de guardar no tienen forma.<br><b>O</b>cupan un recuerdo antes que un lugar.<br><br><b>Y</b> cada persona deja una distinta.<br><b>O</b> quizá solo una sea realmente suya.</div><div class="notes"><div class="note">Fruta<br><small>SALIDA</small></div><div class="note">Pétalos<br><small>CORAZÓN</small></div><div class="note">Vainilla<br><small>FONDO</small></div></div>`;
if(id==='form')return `<p>Ordena las capas de abajo hacia arriba. Usa ↑ y ↓.</p><div id="layers" class="layers"></div><p id="layerResult"></p>`;
return `<p>Los objetos anteriores eran coordenadas de una segunda lectura.</p><div class="fragments"><span class="fragment">15</span><span class="fragment">YO</span><span class="fragment">CAPA</span></div><div class="map-grid"><div class="map-cell">NORTE</div><div class="map-cell">RUTA</div><div class="map-cell">MEMORIA</div><div class="map-cell">EUROPA</div><div class="map-cell">?</div><div class="map-cell">FUTURO</div></div><p>Completa la frase: «Nuestro próximo ________».</p>`;
}
let layerOrder=['W','K','I','I'];
function renderLayers(){let names={K:'01 · Base y patas · K',I:'02 · Cuerpo · I',W:'03 · Cabeza · W'};layers.innerHTML='';layerOrder.forEach((x,i)=>{let row=document.createElement('div');row.className='layer';row.innerHTML='<div class="layer-art">'+names[x]+'</div><div><button type="button" data-dir="-1" data-i="'+i+'">↑</button><button type="button" data-dir="1" data-i="'+i+'">↓</button></div>';layers.append(row)});layers.querySelectorAll('button').forEach(b=>b.onclick=()=>{let i=+b.dataset.i,j=i+(+b.dataset.dir);if(j<0||j>=layerOrder.length)return;[layerOrder[i],layerOrder[j]]=[layerOrder[j],layerOrder[i]];renderLayers();if(layerOrder.join('')==='KIWI')layerResult.textContent='Secuencia reconstruida: K · I · W · I'})}
function openLevel(id){active=C.levels.find(x=>x.id===id);levelCode.textContent='REGISTRO 0'+active.number;levelTitle.textContent=active.title;levelIntro.textContent=active.subtitle;answer.value=state.answers[id]||'';feedback.textContent='';hintCode.value='';hintText.textContent='';puzzle.innerHTML=puzzleHTML(id);show('level');if(id==='orientation')copyCipher.onclick=()=>navigator.clipboard?.writeText('URVD QR HV HO ILQDO');if(id==='form'){layerOrder=['W','K','I','I'];renderLayers()}}
function validate(){return active.answers.map(dec).map(norm).includes(norm(answer.value))}
function revealLevel(){let l=active;if(!state.completed.includes(l.id))state.completed.push(l.id);state.answers[l.id]=answer.value;save();revealTitle.textContent=l.number===1?'Primer vestigio recuperado':l.number===2?'Segundo vestigio recuperado':l.number===3?'Tercer vestigio recuperado':'Ruta abierta';revealText.textContent=l.number===1?'Hay objetos que guardan fotografías, voces y versiones de nosotros mismos. Este empezará a guardar las tuyas: iPhone 15 rosa.':l.number===2?'Una esencia deja una parte de ti allí donde estuviste: Just Moi de Juicy Couture.':l.number===3?'Kiwi será convertido en una figura personalizada impresa en 3D, construida capa a capa.':'Nos iremos de viaje por Europa. La fecha y el destino los elegiremos juntos.';show('reveal',false)}
function renderBook(){pages.innerHTML='';C.levels.forEach(l=>{let done=state.completed.includes(l.id),p=document.createElement('article');p.className='page'+(done?'':' locked');p.innerHTML=done?'<small>PÁGINA 0'+l.number+'</small><strong>'+l.fragment+'</strong><p>'+l.title+'. Fragmento conservado.</p>':'<small>PÁGINA 0'+l.number+'</small><strong>—</strong><p>Contenido fuera de rumbo.</p>';if(done&&l.number===4){let b=document.createElement('button');b.className='secondary';b.textContent='Abrir carta';b.onclick=()=>show('letter',false);p.append(b)}pages.append(p)})}
answerForm.onsubmit=e=>{e.preventDefault();state.attempts[active.id]=(state.attempts[active.id]||0)+1;state.answers[active.id]=answer.value;save();if(validate()){feedback.textContent='La señal coincide.';feedback.className='ok';setTimeout(revealLevel,300)}else{feedback.textContent='La señal no coincide todavía. Revisa el rumbo.';feedback.className='bad'}}
unlockHint.onclick=()=>{let key=norm(hintCode.value).replaceAll(' ','-'),entry=Object.entries(active.hintCodes).find(([k])=>norm(k).replaceAll(' ','-')===key);hintText.textContent=entry?entry[1]:'Código no reconocido.';if(entry){state.hints[active.id]=[...new Set([...(state.hints[active.id]||[]),entry[0]])];save()}}
bootContinue.onclick=()=>show('intro',false);start.onclick=()=>{state.started=true;save();renderHub();show('hub')};back.onclick=()=>{renderHub();show('hub')};document.getElementById('continue').onclick=()=>{renderHub();show('hub')};openBook.onclick=()=>{renderBook();show('book')};closeBook.onclick=()=>{renderHub();show('hub')};closeLetter.onclick=()=>{renderBook();show('book')};
sound.onclick=()=>{state.sound=!state.sound;sound.textContent=state.sound?'●':'◌';save()};
brand.onpointerdown=()=>holdTimer=setTimeout(()=>organizer.showModal(),4000);brand.onpointerup=()=>clearTimeout(holdTimer);brand.onclick=()=>{taps++;clearTimeout(tapTimer);if(taps>=5){taps=0;organizer.showModal()}tapTimer=setTimeout(()=>taps=0,1600)};
orgEnter.onclick=()=>{if(orgPass.value===dec(C.meta.organizerPassword)){orgLogin.hidden=true;orgPanel.hidden=false;renderOrg()}else orgFeedback.textContent='Acceso no verificado.'};
function renderOrg(){orgState.textContent=JSON.stringify(state,null,2);orgControls.innerHTML='';C.levels.forEach(l=>{let b=document.createElement('button');b.className='secondary';b.textContent=(state.completed.includes(l.id)?'Marcar pendiente ':'Completar ')+'Nivel '+l.number;b.onclick=()=>{state.completed=state.completed.includes(l.id)?state.completed.filter(x=>x!==l.id):[...state.completed,l.id];save();renderOrg();renderHub()};orgControls.append(b)})}
simulate.onclick=()=>{state.started=true;state.completed=C.levels.map(x=>x.id);save();renderOrg();renderHub()};reset.onclick=()=>{if(confirm('¿Reiniciar progreso?')){state=fresh();save();location.reload()}};
if(new URLSearchParams(location.search).get('organizer')==='true')organizer.showModal();
function particles(){let c=ambient,x=c.getContext('2d'),ps=[];function rs(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ps=Array.from({length:40},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.3+.3,v:Math.random()*.15+.04,a:Math.random()*.35+.08}))}function t(){x.clearRect(0,0,innerWidth,innerHeight);ps.forEach(p=>{p.y+=p.v;if(p.y>innerHeight)p.y=-3;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fillStyle='rgba(231,180,199,'+p.a+')';x.fill()});requestAnimationFrame(t)}rs();addEventListener('resize',rs);t()}
renderStatus();renderHub();particles();if(state.started)show('hub');else{show('boot',false);bootRun()}
})();